version: "2.0"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      SESSION: $SESSION
      BOT_TOKEN: $BOT_TOKEN
      SUDO_ID: $SUDO_ID
      BOT_NAME: $BOT_NAME
